sudo: required

language: python

services:
  - docker

env:
  variable:
    - DOCKER_UPLOAD=1
  matrix:
    - DOCKER_SERVICE="conangcc54arm"
    - DOCKER_SERVICE="conangcc63arm"
    - DOCKER_SERVICE="conangcc47"

script:
  - docker-compose build ${DOCKER_SERVICE}

after_success:
  - python scripts/deploy.py
