sudo: required

language: python

services:
  - docker

env:
  matrix:
    - DOCKER_SERVICE="conangcc54arm"
    - DOCKER_SERVICE="conangcc63arm"
    - DOCKER_SERVICE="conangcc47"

script:
  - docker-compose build ${DOCKER_SERVICE}

deploy:
  provider: script
  script: env DOCKER_USERNAME=${DOCKER_USERNAME} DOCKER_PASSWORD=${DOCKER_PASSWORD} scripts/deploy.sh
  on:
    branch: master
