sudo: required

language: python

services:
  - docker

env:
  global:
    - DOCKER_UPLOAD="TRUE"
    
  matrix:
    - DOCKER_SERVICE="conangcc54arm"
    - DOCKER_SERVICE="conangcc63arm"
    - DOCKER_SERVICE="conangcc47"

script:
  - python scripts/run.py
