version: '3'
services:
    conangcc54arm:
        build:
            context: gcc54arm
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc54arm:${DOCKER_BUILD_TAG}"
        container_name: conangcc54arm
        volumes:
          - /tmp/install:/tmp/install
        tty: true
        stdin_open: true
    conangcc63arm:
        build:
            context: gcc63arm
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc63arm:${DOCKER_BUILD_TAG}"
        container_name: conangcc63arm
        volumes:
          - /tmp/install:/tmp/install
        tty: true
        stdin_open: true
    conangcc47:
        build:
            context: gcc47
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conangcc47:${DOCKER_BUILD_TAG}"
        container_name: conangcc47
        volumes:
          - /tmp/install:/tmp/install
        tty: true
        stdin_open: true
    msvc15:
        build:
            context: msvc15
            dockerfile: Dockerfile
        image: "${DOCKER_USERNAME}/conanmsvc15:${DOCKER_BUILD_TAG}"
        container_name: conanmsvc15
        tty: true
        stdin_open: true
